resources:
- repo: self

jobs:
- job: windows_x64
  strategy:
    matrix:
      DEBUG_KESTREL:
        UseKestrel: true
        Configuration: debug
      RELEASE_KESTREL:
        UseKestrel: true
        Configuration: release
      DEBUG_HTTPLISTENER:
        UseKestrel: false
        Configuration: debug
      RELEASE_HTTPLISTENER:
        UseKestrel: false
        Configuration: release
  displayName: 'Windows x64'
  timeoutInMinutes: 30
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - powershell: docker pull mcr.microsoft.com/dotnet/core/sdk:3.0.100-rc1-nanoserver-1903
  - powershell: |
      dotnet build -c $(Configuration) src\EventStore.sln
      if (-Not $?) { throw "Exit code is $?" }
    workingDirectory: $(Build.SourcesDirectory)
    displayName: Compile
  - powershell: |
      (Get-ChildItem -Attributes Directory src | % FullName) -Match '.Tests' | `
        ForEach-Object {
          dotnet test -v normal -c $(Configuration) --no-build --logger trx $_ -- RunConfiguration.TargetPlatform=x64
          if (-Not $?) { throw "Exit code is $?" }
        }
    env:
      UseKestrel: $(UseKestrel)
    workingDirectory: $(Build.SourcesDirectory)
    displayName: Test
    errorActionPreference: Stop
  - task: PublishTestResults@2
    displayName: Publish Test Results
    condition: succeededOrFailed()
    inputs:
      testRunTitle: "Windows (.NET Core)"
      platform: "Windows"
      testRunner: VSTest
      testResultsFiles: '**/*.trx'
  - task: PublishBuildArtifacts@1
    condition: eq(variables['System.PullRequest.IsFork'], 'False')
    displayName: Publish Artifacts
    inputs:
      artifactName: windows-net471-$(Configuration) 
      pathToPublish: '$(Build.SourcesDirectory)\bin\'

- job: macos_x64
  strategy:
    matrix:
      DEBUG_KESTREL:
        UseKestrel: true
        Configuration: debug
      RELEASE_KESTREL:
        UseKestrel: true
        Configuration: release
      DEBUG_HTTPLISTENER:
        UseKestrel: false
        Configuration: debug
      RELEASE_HTTPLISTENER:
        UseKestrel: false
        Configuration: release
  displayName: 'macOS x64'
  timeoutInMinutes: 20
  pool:
    vmImage: 'macOS 10.13'
  steps:
  - bash: . '$(Build.SourcesDirectory)/ci/ap-setup-osx.sh'
    displayName: Setup
  - bash: dotnet build -c $(Configuration) src/EventStore.sln
    displayName: Compile
  - bash: find ./src -maxdepth 1 -type d -name "*.Tests" -print0| xargs -0 -n1 dotnet test -v normal -c $(Configuration) --logger trx
    env:
      UseKestrel: $(UseKestrel)
    displayName: Run Tests
  - task: PublishTestResults@2
    displayName: Publish Test Results
    condition: succeededOrFailed()
    inputs:
      testRunTitle: "MacOS 10.13"
      platform: "MacOS 10.13"
      testRunner: VSTest
      testResultsFiles: '**/*.trx'
  - task: PublishBuildArtifacts@1
    condition: eq(variables['System.PullRequest.IsFork'], 'False')
    displayName: Publish Artifacts
    inputs:
      artifactName: macos-{{ variables['Configuration'] }}
      pathToPublish: '$(Build.SourcesDirectory)/bin/'

- job: centos_x64
  strategy:
    matrix:
      DEBUG_KESTREL:
        UseKestrel: true
        Configuration: debug
      RELEASE_KESTREL:
        UseKestrel: true
        Configuration: release
      DEBUG_HTTPLISTENER:
        UseKestrel: false
        Configuration: debug
      RELEASE_HTTPLISTENER:
        UseKestrel: false
        Configuration: release
  displayName: Centos 7 x64
  timeoutInMinutes: 20
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
    - bash: docker pull eventstore/eventstore-ci-centos7:latest
      displayName: Pull Docker image for build
      failOnStderr: false
    - task: Docker@1
      displayName: Compile in CentOS 7 Container
      inputs:
        command: 'run'
        imageName: 'eventstore/eventstore-ci-centos7:latest'
        runInBackground: false
        volumes: '$(Build.SourcesDirectory):/work'
        envVars: |
          EventStoreBuildConfig=$(Configuration)
        containerCommand: ci/ap-build-linux.sh
        workingDirectory: '/work'
    - task: Docker@1
      displayName: Test in CentOS 7 Container
      inputs:
        command: run
        imageName: eventstore/eventstore-ci-centos7:latest
        runInBackground: false
        volumes: '$(Build.SourcesDirectory):/work'
        envVars: |
          EventStoreBuildConfig=$(Configuration)
          UseKestrel=$(UseKestrel)
        containerCommand: ci/ap-test-linux.sh
        workingDirectory: '/work'
    - task: PublishTestResults@2
      displayName: Publish Test Results
      condition: succeededOrFailed()
      inputs:
        testRunTitle: "Centos 7"
        platform: "Centos 7"
        testRunner: VSTest
        testResultsFiles: '**/*.trx'
    - task: PublishBuildArtifacts@1
      condition: eq(variables['System.PullRequest.IsFork'], 'False')
      displayName: Publish Artifacts
      inputs:
        artifactName: centos7-${{ variables['Configuration'] }}
        pathToPublish: '$(Build.SourcesDirectory)/bin/'

- job: ubuntu_x64
  strategy:
    matrix:
      DEBUG_KESTREL:
        UseKestrel: true
        Configuration: debug
      RELEASE_KESTREL:
        UseKestrel: true
        Configuration: release
      DEBUG_HTTPLISTENER:
        UseKestrel: false
        Configuration: debug
      RELEASE_HTTPLISTENER:
        UseKestrel: false
        Configuration: release

  displayName: Ubuntu 14.04 x64
  timeoutInMinutes: 20
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
    - bash: docker pull mcr.microsoft.com/dotnet/core/sdk:3.0.100-rc1-bionic
      displayName: Pull Docker image for build
      failOnStderr: false
    - task: Docker@1
      displayName: Compile in Ubuntu 14.04 Container
      inputs:
        command: 'run'
        imageName: mcr.microsoft.com/dotnet/core/sdk:3.0.100-rc1-bionic
        runInBackground: false
        volumes: '$(Build.SourcesDirectory):/work'
        envVars: |
          EventStoreBuildConfig=$(Configuration)
        containerCommand: ci/ap-build-linux.sh
        workingDirectory: '/work'
    - task: Docker@1
      displayName: Test in Ubuntu 18.04 Container
      inputs:
        command: run
        imageName: mcr.microsoft.com/dotnet/core/sdk:3.0.100-rc1-bionic
        runInBackground: false
        volumes: '$(Build.SourcesDirectory):/work'
        envVars: |
          EventStoreBuildConfig=$(Configuration)
          UseKestrel=$(UseKestrel)
        containerCommand: ci/ap-test-linux.sh
        workingDirectory: '/work'
    - task: PublishTestResults@2
      displayName: Publish Test Results
      condition: succeededOrFailed()
      inputs:
        testRunTitle: "Ubuntu 18.04"
        platform: "Ubuntu 18.04"
        testRunner: VSTest
        testResultsFiles: '**/*.trx'
    - task: PublishBuildArtifacts@1
      condition: eq(variables['System.PullRequest.IsFork'], 'False')
      displayName: Publish Artifacts
      inputs:
        artifactName: ubuntu1404-${{ variables['Configuration'] }}
        pathToPublish: '$(Build.SourcesDirectory)/bin/'